name: MSBuild

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore .\aehd\aehd.sln

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild .\aehd\aehd.sln /p:Platform=x64 /p:Configuration=Release /m /p:OutputPath:.\Output\

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
         name: MSBuild
         path: .
